= Multiple DataSources Sample Task

This is a Spring Boot application that utilizes two DataSources and explicitly configures
which one to be used for the Spring Cloud Task repository.  At this time, the app uses the cloud profile, and is intended to be run on Tanzu Application Service.

== Requirements:

* Java 8 or Above
* Tanzu Application Service instance
* Spring Cloud Data Flow for VMware Tanzu
* Tanzu MySQL

== Classes:

* `MultipleDataSourcesApplication` - the Spring Boot Main Application.
* `SampleCommandLineRunner` - the `CommandLineRunner` implementation for this task.  It outputs the number of `DataSource` beans found in the context (should be 2).
* `DataSourceConfiguration` - Configures two `DataSource` beans.
* `CustomTaskConfigurer` - Uses a Spring `@Qualifier` to specify the correct `DataSource` to use.

== Build:

[source,shell,indent=2]
----
$ mvn clean package
----

== Run on TAS:

. Create a MySQL service instance for your app, this will be the datasource you want to read or write business data from/to.
+
[source,shell,indent=2]
----
$ cf create-service p.mysql db-small myappdb
----
. Create a SCDF service instance
+
[source,shell,indent=2]
----
cf create-service p-dataflow standard data-flow1 -c '{ "relational-data-service": { "name": "p.mysql", "plan": "db-small" }, "messaging-data-service": { "name": "p-rabbitmq", "plan": "standard" }, "skipper-relational": { "name": "p.mysql", "plan": "db-small" }, "scheduler": {"name": "scheduler-for-pcf", "plan": "standard"}, "maven.remote-repositories.repo1.url":"<myRepo>", "maven.remote-repositories.repo1.auth.username":"<myRepoUsername>", "maven.remote-repositories.repo1.auth.password":"<myRepoPassword>"}'
----
. Run the `cf services` command to get the name of the SCDF service instance proxy (eg. something like `relational-5b87cd56-fa4a-4a0b-a392-8c1ea57b3698`).  Update the `dataSource` bean in the `DatasourceConfiguration` class with the service instance name.  Deploy the updated JAR file to your repository.
. Register the task application, either using the SCDF management UI or the SCDF shell CF plugin:
+
[source,shell,indent=2]
----
dataflow:>app register --name multiple-datasources --type task --uri maven://io.spring.cloud:multiple-datasources:2.3.0-SNAPSHOT
Successfully registered application 'task:multiple-datasources'
----
. Create the task.
+
[source,shell,indent=2]
----
dataflow:>task create myTask --definition "multiple-datasources"
Created new task 'myTask'
----
. Launch the task, passing in the 2 database service instance names to bind to.
+
[source,shell,indent=2]
----
dataflow:>task launch --name myTask --properties "deployer.multiple-datasources.cloudfoundry.services=myappdb,relational-5b87cd56-fa4a-4a0b-a392-8c1ea57b3698"
Launched task 'myTask' with execution id 8
----
. Alternatively, schedule the task (assuming you've bound the SCDF server to a scheduler instance).
[source,shell,indent=2]
----
dataflow:>task schedule create --name demoSched --definitionName "myTask" --expression "*/1 * ? * *" --properties "deployer.multiple-datasources.cloudfoundry.services=myappdb,relational-5b87cd56-fa4a-4a0b-a392-8c1ea57b3698"
----
